### ISSUE TITLE
Orchard 1.8.1 Corrupted after installing this module

### ISSUE THREAD

**Issue by matthiasjost** [cscharf/SH.GoogleAnalytics#2]
Server Error in '/' Application.

Ungültiger Objektname 'SH_GoogleAnalytics_GoogleAnalyticsSettingsPartRecord'.
Anweisung(en) konnte(n) nicht vorbereitet werden.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Ungültiger Objektname 'SH_GoogleAnalytics_GoogleAnalyticsSettingsPartRecord'.
Anweisung(en) konnte(n) nicht vorbereitet werden.

Source Error: 

Line 156:                }
Line 157:                else if (@event.LockMode == LockMode.None) {
Line 158:                    @event.Result = ProxyOrLoad(@event, entityPersister, keyToLoad, loadType);
Line 159:                }
Line 160:                else {

Source File: f:\Jost_Matthias\VS-2013-Projects\OrchardSource1-8-1\src\Orchard\Data\Providers\AbstractDataServicesProvider.cs    Line: 158 

Stack Trace: 

[SqlException (0x80131904): Ungültiger Objektname 'SH_GoogleAnalytics_GoogleAnalyticsSettingsPartRecord'.
Anweisung(en) konnte(n) nicht vorbereitet werden.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +388
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +815
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4515
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +69
   System.Data.SqlClient.SqlDataReader.get_MetaData() +134
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +6553981
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) +6556619
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +586
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +104
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +288
   System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) +171
   System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader() +17
   NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\AdoNet\AbstractBatcher.cs:247
   NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Loader.cs:1226
   NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Loader.cs:421
   NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Loader.cs:251
   NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Loader.cs:1279

[GenericADOException: could not load an entity: [SH.GoogleAnalytics.Models.GoogleAnalyticsSettingsPartRecord#1][SQL: SELECT googleanal0_.Id as Id77_0_, googleanal0_.GoogleAnalyticsKey as GoogleAn2_77_0_, googleanal0_.DomainName as DomainName77_0_, googleanal0_.UseAsyncTracking as UseAsync4_77_0_, googleanal0_.TrackOnAdmin as TrackOnA5_77_0_ FROM SH_GoogleAnalytics_GoogleAnalyticsSettingsPartRecord googleanal0_ WHERE googleanal0_.Id=?]]
   NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Loader.cs:1288
   NHibernate.Loader.Entity.AbstractEntityLoader.Load(ISessionImplementor session, Object id, Object optionalObject, Object optionalId) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Entity\AbstractEntityLoader.cs:44
   NHibernate.Loader.Entity.AbstractEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Loader\Entity\AbstractEntityLoader.cs:39
   NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:351
   NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:110
   Orchard.Data.Providers.OrchardLoadEventListener.OnLoad(LoadEvent event, LoadType loadType) in f:\Jost_Matthias\VS-2013-Projects\OrchardSource1-8-1\src\Orchard\Data\Providers\AbstractDataServicesProvider.cs:158
   NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:2527
   NHibernate.Impl.SessionImpl.Get(String entityName, Object id) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:1367
   NHibernate.Impl.SessionImpl.Get(Type entityClass, Object id) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:1303
   NHibernate.Impl.SessionImpl.Get(Object id) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:1287
   Orchard.Data.Repository`1.Get(Int32 id) in f:\Jost_Matthias\VS-2013-Projects\OrchardSource1-8-1\src\Orchard\Data\Repository.cs:87
   Orchard.ContentManagement.Handlers.<>c__DisplayClass1.<Loading>b__0(TRecord prior) in f:\Jost_Matthias\VS-2013-Projects\OrchardSource1-8-1\src\Orchard\ContentManagement\Handlers\StorageFilter.cs:54
   Orchard.ContentManagement.Utilities.LazyField`1.GetValue() in f:\Jost_Matthias\VS-2013-Projects\OrchardSource1-8-1\src\Orchard\ContentManagement\Utilities\LazyField.cs:24
   SH.GoogleAnalytics.Models.GoogleAnalyticsSettingsPart.get_GoogleAnalyticsKey() +16
   SH.GoogleAnalytics.Filters.GoogleAnalyticsFilter.OnResultExecuting(ResultExecutingContext filterContext) +267
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +245
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   Orchard.Mvc.Routes.HttpAsyncHandler.EndProcessRequest(IAsyncResult result) in f:\Jost_Matthias\VS-2013-Projects\OrchardSource1-8-1\src\Orchard\Mvc\Routes\ShellRoute.cs:159
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by cscharf** [comment]
Has the module been configured through the admin panel yet? Trying to figure out the order of events leading to this error.

Thanks,
Chad

**Comment by matthiasjost** [comment]
no. The error occured earlier.

**Comment by cscharf** [comment]
Is it occurring on the admin side or your front-facing site? If the admin side is still functional, and you configure the Google Analytic's properties, does the error still occur?

**Comment by matthiasjost** [comment]
it happened on both sides therefore i removed it. I am working with 1.8.1 (official zip and sql express).

**Comment by cscharf** [comment]
ok, thanks, I will work to reproduce and get back with you, I appreciate the info and assistance.

**Comment by matthiasjost** [comment]
Thats cool. Just drop a message mjost at inteno dot com in case you need anyhting to reproduce. Or post again here.

**Comment by cscharf** [comment]
Hi Matthias, this should be working now, I've gone through and overhauled this plugin for Orchard 1.8+ and was not able to reproduce from a fresh install or my existing instance.

If this is still broken after updating/getting the latest package please let me know and feel free to re-open this issue and will troubleshoot further. Sorry this took a bit.
